common: &default_settings

  status_server_enabled: true
  status_server_port: 18003
  license_key: f71bc0a8a97d1f68ce6f0caea72189a3FFFFNRAL
  custom_attributes:
    nr_deployed_by: WCF-SMS-PREPROD

  agent_enabled: true

  app_name: WCF-SMS-PREPROD

  high_security: false

  enable_auto_app_naming: false

  enable_auto_transaction_naming: true

  log_level: info

  audit_mode: false

  log_file_count: 1

  log_limit_in_kbytes: 0

  log_daily: false

  log_file_name: newrelic_agent.log


  ai_monitoring:

    enabled: false

    record_content:

      enabled: true

  application_logging:

    enabled: true

    forwarding:

      enabled: true


      context_data:

        enabled: false



    metrics:

      enabled: true



  code_level_metrics:

    enabled: true


  max_stack_trace_lines: 30

  attributes:

    enabled: true




    http_attribute_mode: both

  transaction_tracer:

    enabled: true

    transaction_threshold: apdex_f

    record_sql: obfuscated

    log_sql: false

    stack_trace_threshold: 0.5

    explain_enabled: true

    explain_threshold: 0.5

    top_n: 20

  error_collector:

    enabled: true

    ignore_classes:
      - "akka.actor.ActorKilledException"

    ignore_status_codes: 404

  transaction_events:

    enabled: true

    max_samples_stored: 2000

  distributed_tracing:

    enabled: true

    exclude_newrelic_header: false

  span_events:

    enabled: true

    max_samples_stored: 2000

    attributes:

      enabled: true



  thread_profiler:

    enabled: true

  browser_monitoring:

    auto_instrument: true

    tag_lib_instrument: false

    tag_lib_head_pattern: '<head>'

  class_transformer:

    com.newrelic.instrumentation.servlet-user:
      enabled: false

    com.newrelic.instrumentation.spring-aop-2:
      enabled: false

    com.newrelic.instrumentation.jdbc-resultset:
      enabled: false

    classloader_excludes:
      groovy.lang.GroovyClassLoader$InnerLoader,
      org.codehaus.groovy.runtime.callsite.CallSiteClassLoader,
      com.collaxa.cube.engine.deployment.BPELClassLoader,
      org.springframework.data.convert.ClassGeneratingEntityInstantiator$ObjectInstantiatorClassGenerator,
      org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader,
      gw.internal.gosu.compiler.SingleServingGosuClassLoader,

    enhanced_spring_transaction_naming: false

  jfr:

    enabled: false

    audit_logging: false

  labels:


  security:
    enabled: false

    mode: IAST

    validator_service_url: wss://csec.nr-data.net

    agent:
      enabled: false

    detection:
      rci:
        enabled: true
      rxss:
        enabled: true
      deserialization:
        enabled: true

  slow_transactions:
    enabled: true
    threshold: 600000

    evaluate_completed_transactions: false



development:
  <<: *default_settings
  app_name: My Application (Development)

test:
  <<: *default_settings
  app_name: My Application (Test)

production:
  <<: *default_settings

staging:
  <<: *default_settings
  app_name: My Application (Staging)
